package Tasks;

import org.jsoup.nodes.Document;

import java.util.HashMap;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Interprets the data generated by the PageRetrieverTask
 */
@Deprecated
public class DataGathererTask extends Task {
    public static final int PRIORITY = -1;
    private final String page;
    public DataGathererTask(SharedData sharedData, String page, int linkCount) {
        super(sharedData,PRIORITY);
        this.page = page;
    }

    @Override
    public void run() {
        //System.out.println("start DataGathererTask");

        //moved to PageParser
        /*getSharedData().updateRuntime();
        DataSnapshot snapshot = getSharedData().getSnapshot();
        snapshot.pageParsed = page;
        this.addGeneratedTask(new ReporterTask(getSharedData(),snapshot));

        //moved to ReporterTask
        getSharedData().checkOvermax();*/

        //System.out.println("end DataGathererTask");
    }
}
